// All emoji animation CSS removed; dotLottie handles all animation now.

const BASE_ROOM_EMOJIS = [
  { id: "fist", src: "/emojis/lottie ( Fist).lottie", label: "Fist", flip: false, type: "dotlottie" },
  { id: "imp_smile", src: "/emojis/lottie ( Imp-smile).lottie", label: "Imp smile", flip: false, type: "dotlottie" },
  { id: "kissing_cl", src: "/emojis/lottie ( Kissing-cl).lottie", label: "Kissing", flip: false, type: "dotlottie" },
  { id: "kissing_he", src: "/emojis/lottie ( Kissing-he).lottie", label: "Kissing heart", flip: false, type: "dotlottie" },
  { id: "biting_lip", src: "/emojis/lottie (Biting-lip).lottie", label: "Biting lip", flip: false, type: "dotlottie" },
  { id: "blush", src: "/emojis/lottie (Blush).lottie", label: "Blush", flip: false, type: "dotlottie" },
  { id: "clap", src: "/emojis/lottie (Clap).lottie", label: "Clap", flip: false, type: "dotlottie" },
  { id: "dancer", src: "/emojis/lottie (Dancer).lottie", label: "Dancer", flip: false, type: "dotlottie" },
  { id: "donkey", src: "/emojis/lottie (Donkey).lottie", label: "Donkey", flip: false, type: "dotlottie" },
  { id: "grin_sweat", src: "/emojis/lottie (Grin-sweat).lottie", label: "Grin sweat", flip: false, type: "dotlottie" },
  { id: "grinning", src: "/emojis/lottie (Grinning).lottie", label: "Grinning", flip: false, type: "dotlottie" },
  { id: "happy_cry", src: "/emojis/lottie (Happy-cry).lottie", label: "Happy cry", flip: false, type: "dotlottie" },
  { id: "heart_eye", src: "/emojis/lottie (Heart-eye).lottie", label: "Heart eye", flip: false, type: "dotlottie" },
  { id: "heart_eyes", src: "/emojis/lottie (Heart-eyes).lottie", label: "Heart eyes", flip: false, type: "dotlottie" },
  { id: "heart_face", src: "/emojis/lottie (Heart-face).lottie", label: "Heart face", flip: false, type: "dotlottie" },
  { id: "heart_hand", src: "/emojis/lottie (Heart-hand).lottie", label: "Heart hand", flip: false, type: "dotlottie" },
  { id: "joy", src: "/emojis/lottie (Joy).lottie", label: "Joy", flip: false, type: "dotlottie" },
  { id: "kiss", src: "/emojis/lottie (Kiss).lottie", label: "Kiss", flip: false, type: "dotlottie" },
  { id: "kissing", src: "/emojis/lottie (Kissing).lottie", label: "Kissing", flip: false, type: "dotlottie" },
  { id: "laughing", src: "/emojis/lottie (Laughing).lottie", label: "Laughing", flip: false, type: "dotlottie" },
  { id: "loudly", src: "/emojis/lottie (Loudly).lottie", label: "Loudly", flip: false, type: "dotlottie" },
  { id: "money_face", src: "/emojis/lottie (Money-face).lottie", label: "Money face", flip: false, type: "dotlottie" },
  { id: "partying_fa", src: "/emojis/lottie (Partying-fa).lottie", label: "Partying", flip: false, type: "dotlottie" },
  { id: "peeking", src: "/emojis/lottie (Peeking).lottie", label: "Peeking", flip: false, type: "dotlottie" },
  { id: "pensive", src: "/emojis/lottie (Pensive).lottie", label: "Pensive", flip: false, type: "dotlottie" },
  { id: "rage", src: "/emojis/lottie (Rage).lottie", label: "Rage", flip: false, type: "dotlottie" },
  { id: "rofl", src: "/emojis/lottie (Rofl).lottie", label: "Rofl", flip: false, type: "dotlottie" },
  { id: "rose", src: "/emojis/lottie (Rose).lottie", label: "Rose", flip: false, type: "dotlottie" },
  { id: "salute", src: "/emojis/lottie (Salute).lottie", label: "Salute", flip: false, type: "dotlottie" },
  { id: "see_no_e", src: "/emojis/lottie (See-no-e).lottie", label: "See no evil", flip: false, type: "dotlottie" },
  { id: "shushing", src: "/emojis/lottie (Shushing).lottie", label: "Shushing", flip: false, type: "dotlottie" },
  { id: "sleep", src: "/emojis/lottie (Sleep).lottie", label: "Sleep", flip: false, type: "dotlottie" },
  { id: "smile", src: "/emojis/lottie (Smile).lottie", label: "Smile", flip: false, type: "dotlottie" },
  { id: "sneeze", src: "/emojis/lottie (Sneeze).lottie", label: "Sneeze", flip: false, type: "dotlottie" },
  { id: "star_struck", src: "/emojis/lottie (Star-struck).lottie", label: "Star struck", flip: false, type: "dotlottie" },
  { id: "sunglass", src: "/emojis/lottie (Sunglass).lottie", label: "Sunglass", flip: false, type: "dotlottie" },
  { id: "thermom", src: "/emojis/lottie (Thermom).lottie", label: "Thermom", flip: false, type: "dotlottie" },
  { id: "thinking", src: "/emojis/lottie (Thinking).lottie", label: "Thinking", flip: false, type: "dotlottie" },
  { id: "revolving_heart", src: "/emojis/lottie (u1f49e · Revolving).lottie", label: "Revolving heart", flip: false, type: "dotlottie" },
  { id: "wink", src: "/emojis/lottie (Wink).lottie", label: "Wink", flip: false, type: "dotlottie" },
  { id: "yawn", src: "/emojis/lottie (Yawn).lottie", label: "Yawn", flip: false, type: "dotlottie" },
  { id: "yum", src: "/emojis/lottie (Yum).lottie", label: "Yum", flip: false, type: "dotlottie" },
  { id: "zany_face", src: "/emojis/lottie (Zany-face).lottie", label: "Zany face", flip: false, type: "dotlottie" },
  { id: "zipper_face", src: "/emojis/lottie (Zipper-face).lottie", label: "Zipper face", flip: false, type: "dotlottie" },
  { id: "clinking_short", src: "/emojis/lottie Clinking-.lottie", label: "Clinking", flip: false, type: "dotlottie" },
  { id: "running", src: "/emojis/lottie Running.lottie", label: "Running", flip: false, type: "dotlottie" },
  { id: "alarm_clock", src: "/emojis/lottie,Alarm-clockjson.lottie", label: "Alarm clock", flip: false, type: "dotlottie" },
  { id: "bomb", src: "/emojis/lottieBomb.lottie", label: "Bomb", flip: false, type: "dotlottie" },
  { id: "bottle", src: "/emojis/lottieBottle.lottie", label: "Bottle", flip: false, type: "dotlottie" },
  { id: "clinking", src: "/emojis/lottieClinking.lottie", label: "Clinking", flip: false, type: "dotlottie" },
];

export const ROOM_EMOJIS = BASE_ROOM_EMOJIS;