// All emoji animation CSS removed; Lottie handles all animation now.
const BASE_ROOM_EMOJIS = [
  { id: "e1",  src: "/emojis/lottie (1).json",  label: "reaction 1",  flip: false, type: "lottie" },
  { id: "e2",  src: "/emojis/lottie (2).json",  label: "reaction 2",  flip: false, type: "lottie" },
  { id: "e3",  src: "/emojis/lottie (3).json",  label: "reaction 3",  flip: false, type: "lottie" },
  { id: "e3f", src: "/emojis/lottie (3).json",  label: "reaction 3 flip", flip: true, type: "lottie" },
  { id: "e4",  src: "/emojis/lottie (4).json",  label: "reaction 4",  flip: false, type: "lottie" },
  { id: "e5",  src: "/emojis/lottie (5).json",  label: "reaction 5",  flip: false, type: "lottie" },
  { id: "e6",  src: "/emojis/lottie (6).json",  label: "reaction 6",  flip: false, type: "lottie" },
  { id: "e7",  src: "/emojis/lottie (7).json",  label: "reaction 7",  flip: false, type: "lottie" },
  { id: "e8",  src: "/emojis/lottie (8).json",  label: "reaction 8",  flip: false, type: "lottie" },
  { id: "e9",  src: "/emojis/lottie (9).json",  label: "reaction 9",  flip: false, type: "lottie" },
  { id: "e10", src: "/emojis/lottie (10).json", label: "reaction 10", flip: false, type: "lottie" },
  { id: "e11", src: "/emojis/lottie (11).json", label: "reaction 11", flip: false, type: "lottie" },
  { id: "e12", src: "/emojis/lottie (12).json", label: "reaction 12", flip: false, type: "lottie" },
  { id: "e13", src: "/emojis/lottie (13).json", label: "reaction 13", flip: false, type: "lottie" },
  { id: "e14", src: "/emojis/lottie (14).json", label: "reaction 14", flip: false, type: "lottie" },
  { id: "e15", src: "/emojis/lottie (15).json", label: "reaction 15", flip: false, type: "lottie" },
  { id: "e16", src: "/emojis/lottie (16).json", label: "reaction 16", flip: false, type: "lottie" },
  { id: "e17", src: "/emojis/lottie (17).json", label: "reaction 17", flip: false, type: "lottie" },
  { id: "e18", src: "/emojis/lottie (18).json", label: "reaction 18", flip: false, type: "lottie" },
  { id: "e19", src: "/emojis/lottie (19).json", label: "reaction 19", flip: false, type: "lottie" },
  { id: "e20", src: "/emojis/lottie (20).json", label: "reaction 20", flip: false, type: "lottie" },
  { id: "e21", src: "/emojis/lottie (21).json", label: "reaction 21", flip: false, type: "lottie" },
  { id: "e22", src: "/emojis/lottie (22).json", label: "reaction 22", flip: false, type: "lottie" },
  { id: "e23", src: "/emojis/lottie (23).json", label: "reaction 23", flip: false, type: "lottie" },
  { id: "e24", src: "/emojis/lottie (24).json", label: "reaction 24", flip: false, type: "lottie" },
  { id: "e25", src: "/emojis/lottie (25).json", label: "reaction 25", flip: false, type: "lottie" },
  { id: "e26", src: "/emojis/lottie (26).json", label: "reaction 26", flip: false, type: "lottie" },
  { id: "e27", src: "/emojis/lottie (27).json", label: "reaction 27", flip: false, type: "lottie" },
  { id: "e28", src: "/emojis/lottie (28).json", label: "reaction 28", flip: false, type: "lottie" },
  { id: "e29", src: "/emojis/lottie (29).json", label: "reaction 29", flip: false, type: "lottie" },
  { id: "e30", src: "/emojis/lottie (30).json", label: "reaction 30", flip: false, type: "lottie" },
  { id: "e31", src: "/emojis/lottie (31).json", label: "reaction 31", flip: false, type: "lottie" },
  { id: "e32", src: "/emojis/lottie (32).json", label: "reaction 32", flip: false, type: "lottie" },
  { id: "e33", src: "/emojis/lottie (33).json", label: "reaction 33", flip: false, type: "lottie" },
  { id: "e34", src: "/room-emojis/e34.json", label: "reaction 34", flip: false, type: "lottie" },
  { id: "e35", src: "/room-emojis/e35.json", label: "reaction 35", flip: false, type: "lottie" },
  { id: "e36", src: "/room-emojis/e36.json", label: "reaction 36", flip: false, type: "lottie" },
  { id: "e37", src: "/room-emojis/e37.json", label: "reaction 37", flip: false, type: "lottie" },
  { id: "e38", src: "/room-emojis/e38.json", label: "reaction 38", flip: false, type: "lottie" },
  { id: "e39", src: "/room-emojis/e39.json", label: "reaction 39", flip: false, type: "lottie" },
  { id: "e40", src: "/room-emojis/e40.json", label: "reaction 40", flip: false, type: "lottie" },
  { id: "e41", src: "/room-emojis/e41.json", label: "reaction 41", flip: false, type: "lottie" },
  { id: "e42", src: "/room-emojis/e42.json", label: "reaction 42", flip: false, type: "lottie" },
  { id: "e43", src: "/room-emojis/e43.json", label: "reaction 43", flip: false, type: "lottie" },
  { id: "e44", src: "/room-emojis/e44.json", label: "reaction 44", flip: false, type: "lottie" },
  { id: "e45", src: "/room-emojis/e45.json", label: "reaction 45", flip: false, type: "lottie" },
  { id: "e46", src: "/room-emojis/e46.json", label: "reaction 46", flip: false, type: "lottie" },
  { id: "e47", src: "/room-emojis/e47.json", label: "reaction 47", flip: false, type: "lottie" },
  { id: "e48", src: "/room-emojis/e48.json", label: "reaction 48", flip: false, type: "lottie" },
  { id: "e49", src: "/room-emojis/e49.json", label: "reaction 49", flip: false, type: "lottie" },
  { id: "e50", src: "/room-emojis/e50.json", label: "reaction 50", flip: false, type: "lottie" },
  { id: "e51", src: "/room-emojis/e51.json", label: "reaction 51", flip: false, type: "lottie" },
  { id: "e52", src: "/room-emojis/e52.json", label: "reaction 52", flip: false, type: "lottie" },
  { id: "e53", src: "/room-emojis/e53.json", label: "reaction 53", flip: false, type: "lottie" },
  { id: "e54", src: "/room-emojis/e54.json", label: "reaction 54", flip: false, type: "lottie" },
];

export const ROOM_EMOJIS = BASE_ROOM_EMOJIS;
